language: scala
sudo: required
dist: trusty

before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.0/bin/travis_setup.sh | bash -x

jdk:
  - oraclejdk8
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
  - 2.13.0-M1
matrix:
  include:
    - scala: 2.10.6
      jdk: openjdk7

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
